[package]
name = "bff-gui"
version = "0.1.0"
authors = ["widberg"]
edition = "2021"

[dependencies]
bff = { path = "../bff" }
eframe = "0.23.0"
egui_extras = { version = "0.23.0", features = ["all_loaders"] }
image = { version = "0.24.7", features = ["dds", "png"] }
rfd = "0.12.0"
serde = "1.0.188"
serde_json = "1.0.107"
