[package]
name = "bff-gui"
version = "0.1.0"
authors = ["widberg", "pizzart"]
edition = "2021"
rust-version = "1.72.1"

[dependencies]
bff = { path = "../bff" }
derive_more = "0.99.17"
eframe = "0.23.0"
egui = "0.23.0"
egui_extras = { version = "0.23.0", features = ["image"], default-features = false }
hound = "3.5.1"
image = { version = "0.24.7", features = ["dds", "png"], default-features = false }
rfd = "0.12.0"
rodio = { version = "0.17.1", features = ["wav"], default-features = false }
serde = "1.0.188"
serde_json = "1.0.107"
three-d = "0.16.1"
three-d-asset = "0.6.0"
tokio = { version = "1.33.0", features = ["rt-multi-thread", "time"] }
