[package]
name = "bff"
version = "0.1.0"
authors = ["widberg"]
edition = "2021"

[dependencies]
ascii = { version = "1.1.0", features = ["serde"] }
bff-derive = { path = "../bff-derive", version = "*" }
bilge = "0.2.0"
binrw = "0.12.0"
derive_more = "0.99.17"
indexmap = { version = "2.0.0", features = ["serde"] }
num-traits = "0.2.15"
serde = { version = "1.0.160", features = ["derive"] }
serde-big-array = "0.5.1"

[dev-dependencies]
test-generator = "0.3.1"
