[package]
name = "bff"
version = "0.1.0"
authors = ["widberg"]
edition = "2021"

[dependencies]
ascii = { version = "1.1.0", features = ["serde"] }
binrw = "0.11.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
