[package]
name = "bff"
version = "0.1.0"
authors = ["widberg"]
edition = "2021"

[dependencies]
ascii = { version = "1.1.0", features = ["serde"] }
binrw = "0.11.2"
serde = { version = "1.0.160", features = ["derive"] }
derive_more = "0.99.17"
num-traits = "0.2.15"

[dev-dependencies]
test-generator = "0.3.1"
