use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::names::Name;
use crate::source::keyframer::SourceLinearTrack;

pub type SourceMessageTrack = SourceLinearTrack<Vec<SourceMessage>>;

#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SourceMessage {
    Command {
        command: SourceMessageKind,
        args: Vec<String>,
    },
    Raw {
        message_id: u32,
        u32_param: Name,
        flag_param: u32,
        float_param: f32,
        name_param: Name,
    },
}

#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum SourceMessageKind {
    MsgNoMessage,
    MsgAnimNoteTrackFirst,
    MsgSkelCollide,
    MsgAnimLoop,
    MsgAnimNosmooth,
    MsgAnimSmoothratio,
    MsgAnimNodeCollide,
    MsgAnimNodeUncollide,
    MsgAnimNodeGetorient,
    MsgAnimOrient,
    MsgAnimNoorient,
    MsgAnimAction,
    MsgAnimLoopStart,
    MsgAnimLoopEnd,
    MsgAnimNodynamic,
    MsgAnimDynamic,
    MsgAnimMaterialColor,
    MsgAnimActivateAnimatedObject,
    MsgAnimDeactivateAnimatedObject,
    MsgAnimHide,
    MsgAnimUnhide,
    MsgAnimReset,
    MsgAnimReplay,
    MsgAnimPause,
    MsgAnimResume,
    MsgAnimPlayDialog,
    MsgAnimStopDialog,
    MsgAnimLoadDialog,
    MsgAnimUnknownSkelCollide,
    MsgAnimHitSkelCollide,
    MsgAnimParticlesEfx,
    MsgAnimParticlesEfxPause,
    MsgAnimParticlesEfxReset,
    MsgAnimPlaySound,
    MsgAnimStopSound,
    MsgAnimHideNode,
    MsgAnimUnhideNode,
    MsgAnimSetAnim,
    MsgAnimStartMaterialAnim,
    MsgAnimStopMaterialAnim,
    MsgAnimPauseMaterialAnim,
    MsgRtcPicture,
    MsgRscNoteTrackEnd,
    MsgRtcStarted,
    MsgRtcEnded,
    MsgRtcChangecamera,
    MsgRtcNoPicture,
    MsgRtcMark,
    MsgRtcLetterBoxStart,
    MsgRtcLetterBoxEnd,
    MsgRtcLetterBoxColor,
    MsgAnimNoteTrackEnd,
    MsgGotoCurlength,
    #[serde(rename = "msg_goto_2nd_vertex")]
    MsgGoto2ndVertex,
    MsgGotoEnd,
    MsgVolumeIn,
    MsgVolumeOut,
    MsgVolumeStay,
    MsgVolumeAnimReset,
    MsgAnimStopallsound,
    MsgAnimNodeStopalldialog,
    MsgCarryBegin,
    MsgCarryEnd,
    MsgHeldBegin,
    MsgHeldEnd,
    MsgThrownBegin,
    MsgThrownEnd,
    MsgTargetHit,
    MsgTargetMiss,
    MsgLodCollide,
    MsgDecorCollide,
    MsgThrownLodCollide,
    MsgThrownDecorCollide,
    MsgRestoreCollide,
    MsgSequencedCollide,
    MsgSkinActBegin,
    MsgSkinActEnd,
    MsgBumper,
    MsgCameraCapturePatchStart,
    MsgCameraCaptureFrameStart,
    MsgCameraCaptureTextureStart,
    MsgCameraCaptureEnd,
    #[serde(rename = "msg_camera_capture_param_1")]
    MsgCameraCaptureParam1,
    #[serde(rename = "msg_camera_capture_param_2")]
    MsgCameraCaptureParam2,
    #[serde(rename = "msg_camera_capture_param_3")]
    MsgCameraCaptureParam3,
    MsgCameraResetFocus,
    MsgStreamEnd,
    MsgStreamErrorInit,
    MsgStreamError,
    MsgStreamErrorTrayopen,
    MsgStreamResumed,
    MsgStreamResumePossible,
    MsgStreamAbort,
    MsgStreamAborted,
    MsgGameActivated,
    MsgGameDeactivated,
    MsgGameReseted,
    MsgAnimFramelink,
    MsgAnimFrameunlink,
    MsgAvirer,
    MsgOccluderOn,
    MsgOccluderOff,
    MsgStencilOn,
    MsgStencilOff,
    MsgEngineEnd,
    MsgCollisionPlayerIn,
    MsgCollisionPlayerOut,
    MsgEndCheckPlayer,
    MsgStartCheckRespawn,
    MsgCheckPlayer,
    MsgRespawn,
    MsgResetBaseAgent,
    MsgRtcScriptInterpCommand,
    MsgRtcScriptCheckSkipRtc,
    MsgRtcScriptCheckSkipText,
    MsgMenuActivateGame,
    MsgRtcScriptCheckEndGoto,
    MsgNoteTrackSample,
    MsgToLevel,
    MsgChangeLevel,
    MsgToMenu,
    MsgStartMenu,
    MsgRtcRetrieveNode,
    MsgRtcOrientNodes,
    MsgRtcHideNode,
    MsgRtcUnhideNode,
    MsgRtcControlStrip,
    MsgRtcSetCameraGame,
    MsgRtcSetCameraChase,
    MsgRtcSetCameraTravelling,
    MsgRtcSetCameraForce,
    MsgRtcSetCameraForceTravelling,
    MsgRtcSetCameraFocus,
    MsgRtcSetCameraDialog,
    MsgRtcCameraCut,
    MsgRtcCameraSmooth,
    MsgRtcPlayAnim,
    MsgRtcGoto,
    MsgRtcSkip,
    MsgRtcClearText,
    MsgRtcStartCountdown,
    MsgRtcSetDof,
    MsgRtcEndOfRtc,
    MsgRtcDisableSkip,
    MsgRtcDoFade,
    MsgRtcWait,
    MsgRtcSetText,
    MsgRtcWaitAnim,
    MsgRtcPlayDialog,
    MsgRtcPosPerso,
    MsgRtcPosVehicle,
    MsgRtcWaitGoto,
    MsgRtcStartAnimframe,
    MsgRtcStartRtcFx,
    MsgRtcChangeSmoothAnim,
    MsgRtcPlaySound,
    MsgRtcUnhideAllCreatures,
    MsgRtcUnkSl,
    MsgEnterTeleport,
    MsgEnterTeleportAlternative,
    MsgExecuteTeleport,
    MsgWarpColorCheck,
    MsgWarpColorCheck2,
    MsgWarpColorDontCheck,
    MsgBlockFader,
    MsgFxTraceBStart,
    MsgFxTraceBEnd,
    MsgFxTraceEStart,
    MsgFxTraceEEnd,
    MsgBreak,
    MsgGenerateObject,
    MsgExecuteTeleportEnd,
    MsgFootOnGroundBone,
    MsgFootprintOnGround,
    MsgAnimChange,
    MsgDeactivateSceneOmnis,
    MsgActivateSceneOmnis,
    MsgActionInEventVolume,
    MsgExplosionEventVolume,
    MsgImpactable,
    MsgLockPos,
    MsgUnlockPos,
    #[serde(rename = "msg_contextual_sound_1")]
    MsgContextualSound1,
    #[serde(rename = "msg_contextual_sound_2")]
    MsgContextualSound2,
    MsgSoundClothe,
    MsgHit,
    MsgUnhit,
    MsgEvent,
    MsgStartMission,
    MsgCheckPlayerDistMission,
    MsgCheckRespawnSpecific,
    MsgStartBlind,
    MsgFinishBlind,
    MsgOnGround,
    MsgItCarryingRespawnTeleport,
}
