[package]
name = "bff-cli"
version = "0.1.0"
authors = ["widberg"]
edition = "2021"
build = "build.rs"

[dependencies]
bff = { path = "../bff" }
clap = { version = "4.2.4", features = ["derive"] }
derive_more = "0.99.17"
pathdiff = "0.2.1"
serde_json = "1.0.96"
shadow-rs = "0.25.0"

[build-dependencies]
shadow-rs = "0.25.0"

[lints]
workspace = true
