[package]
name = "bff-derive"
version = "0.1.0"
authors = ["widberg"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.66"
quote = "1.0.31"
syn = { version = "2.0.27", features = ["full"] }
